title: Teki Solves
description: Web Design, Development, SEO, Digital Art & Tutoring
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tekisolves.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-seo-tag