- id: 1
  name: "Unity From Zero to Proficiency: Create Your First Game Fast"
  description: Master Unity quickly with this step-by-step guide for creating 2D & 3D games.
  link: "https://www.amazon.com/Unity-Proficiency-Foundations-step-step/dp/179580663X?crid=2SLB90EYXUQKU&dib=eyJ2IjoiMSJ9.R5Sf9Cwgnli9lgqobpyXlIsqgYr4HIFMbOlgrzNpwq5qBM-selm3thN_Llld7z26BP9dthfxvNpo_NfbrtzZmGOmWaBhknaVYP4vd4XmfMLAmkOz0X7juJxukzYqTSB7.uuQhb0Z14O64R8Mi0rYKpVoDxlJGm00LVcAYWT1j6Kw&dib_tag=se&keywords=Unity+From+Zero+to+Proficiency%2C+Create+Your+First+Game&qid=1727983032&sprefix=unity+from+zero+to+proficiency%2C+create+your+first+game%2Caps%2C334&sr=8-1&linkCode=ll1&tag=tekisolves-20&linkId=28c25788420fc54a890d13bb6d85d2c4&language=en_US&ref_=as_li_ss_tl"
  image_url: "/unity.jpg"
  rating: "★★★★☆"

- id: 2
  name: Blueprints Visual Scripting, Master Unreal Engine 5 Fast
  description: Learn UE5 Blueprints to create games, UI, AI, and VR without coding.
  link: "https://www.amazon.com/Blueprints-Visual-Scripting-Unreal-Engine/dp/180181158X?crid=1BUR16HJDBHFP&dib=eyJ2IjoiMSJ9.eoMi1KFUPn3zQSbcZw8w31GRmKx6o0fHf3SMlWWx_SzGjHj071QN20LucGBJIEps.P4ErzMwxeo9C2wYJjP3EL5aRq7GUXB_pELx7rL5JXos&dib_tag=se&keywords=Blueprints+Visual+Scripting%3A+Master+Unreal+Engine+5+Fast&qid=1727983456&sprefix=blueprints+visual+scripting+master+unreal+engine+5+fast%2Caps%2C343&sr=8-1&linkCode=ll1&tag=tekisolves-20&linkId=e1b2e307290ee7de5e67a53ea009fffb&language=en_US&ref_=as_li_ss_tl"
  image_url: "/unreal.jpg"
  rating: "★★★★☆"

- id: 3
  name: Intro to GameMaker Studio 2, Design & Program Games Fast
  description: Master GameMaker Studio 2.1 and GML programming to create your own games.
  link: "https://www.amazon.com/GameMaker-Studio-Introduction-Design-Programming-ebook/dp/B0876HGFSR?crid=37ZP87126CQ37&dib=eyJ2IjoiMSJ9.0-IJ5Ie1uuPCTHbSwGkmPvdtk0_pzIZvxaTkcXQRdhrGjHj071QN20LucGBJIEps.7kNgMVtFpnZmIvkseXXpJBsfcbpzHED3LYF4bSeCGOQ&dib_tag=se&keywords=GameMaker+Studio+2+Introduction+To+Game+Design+%26+Programming+%28Learn+GameMaker+Studio+2%29.&qid=1727983801&sprefix=gamemaker+studio+2+introduction+to+game+design+%26+programming+learn+gamemaker+studio+2+.%2Caps%2C168&sr=8-1&linkCode=ll1&tag=tekisolves-20&linkId=0a89f6dd458035e47964ec3c291684af&language=en_US&ref_=as_li_ss_tl"
  image_url: "/gamemaker.jpg"
  rating: "★★★☆☆"

- id: 4
  name: CryEngine Game Dev Blueprints, Master Game Creation
  description: Create CRYENGINE games with step-by-step projects, covering AI, menus, and animation.
  link: "https://www.amazon.com/CryEngine-Development-Blueprints-Richard-Marcoux/dp/1784399876?crid=1P7PUN99CHVR0&dib=eyJ2IjoiMSJ9.pkAq_UZCVbYQVn0BPeqCBg.RJrtqUHGE9uuyc1Tr63pGReHxijRegpoOgu3DmeImsI&dib_tag=se&keywords=Cryengine+Game+Development+Blueprints.&qid=1727983985&sprefix=cryengine+game+development+blueprints.%2Caps%2C304&sr=8-1&linkCode=ll1&tag=tekisolves-20&linkId=860e792c26b38a32d1c39571f2760799&language=en_US&ref_=as_li_ss_tl"
  image_url: "/cryengine.jpg"
  rating: "★★★★☆"

- id: 5
  name: Blender All-in-One For Dummies, Master 3D Animation
  description: Learn 3D animation with Blender, from modeling to rendering. Perfect for beginners and experienced users alike.
  link: "https://www.amazon.com/s?k=Blender+All-in-One+For+Dummies.&crid=1T84UVO8PV67L&sprefix=blender+all-in-one+for+dummies.%2Caps%2C318&linkCode=ll2&tag=tekisolves-20&linkId=4a0162655b623a477fde7257e4de01f3&language=en_US&ref_=as_li_ss_tl"
  image_url: "/blender.jpg"
  rating: "★★★★★"

- id: 6
  name: Visual Studio Bible, Master Development Tools for Enhanced Productivity
  description: Unlock the full potential of Visual Studio 2024 with easy lessons, cool tricks, and collaborative tools. Perfect for both newcomers and experts!
  link: "https://www.amazon.com/s?k=Visual+Studio+Bible%3A+Everything+You+Need+to+Know+to+Master+Features+and+Tools+for+Increased+Productivity.&crid=9FM4E1CYT67K&sprefix=visual+studio+bible+everything+you+need+to+know+to+master+features+and+tools+for+increased+productivity.%2Caps%2C219&linkCode=ll2&tag=tekisolves-20&linkId=31bdfb1cfbe1dabb57d9c71bc0f4aeeb&language=en_US&ref_=as_li_ss_tl"
  image_url: "/visual-studio.jpg"
  rating: "★★★★☆"

- id: 7
  name: Construct 3 Game Creation Tips for Beginners
  description: Essential tips for creating 2D games in Construct 3 without coding.
  link: "https://www.amazon.com/s?k=Construct+3+Game+Creation+Tips+%26+Techniques%3A+for+Absolute+Beginners+%28GameENGINES+Game+Creation+Series%29&crid=3LS8NO20Y13YZ&sprefix=construct+3+game+creation+tips+%26+techniques+for+absolute+beginners+gameengines+game+creation+series+%2Caps%2C176&linkCode=ll2&tag=tekisolves-20&linkId=f48c686504fbb1b7c21d808276f8f8b3&language=en_US&ref_=as_li_ss_tl"
  image_url: "/construct3.jpg"
  rating: "★★★★☆"
  
- id: 8
  name: Game Audio with FMOD and Unity
  description: Learn game audio principles through FPS game creation using Unity and FMOD.
  link: "https://www.amazon.com/Game-Audio-Unity-Ciar%C3%A1n-Robinson/dp/1138315974?crid=171P4N56HJUBW&dib=eyJ2IjoiMSJ9.Pu0m2lrDy-X7coGO_1OGqQUzVuAX5V2LNYHM2Cqq17U.yACqy0qJYcbXnBRe1RAACD5jL1vLrEz_a4SzomtrfYc&dib_tag=se&keywords=Game+Audio+with+FMOD+and+Unity.&qid=1727985055&sprefix=game+audio+with+fmod+and+unity.%2Caps%2C185&sr=8-1&linkCode=ll1&tag=tekisolves-20&linkId=572d1ca18b27afc14d8f14b4231a6099&language=en_US&ref_=as_li_ss_tl"
  image_url: "/game-audio.jpg"
  rating: "★★★★★"
  
- id: 9
  name: Realistic Asset Creation with Adobe Substance 3D
  description: Master 3D design with Adobe Substance 3D using interactive projects. Build a portfolio!
  link: "https://www.amazon.com/Realistic-Asset-Creation-Adobe-Substance/dp/1803233400?crid=23B24KUEJHB7J&dib=eyJ2IjoiMSJ9.9qaHkO3Bm-dcFmpv-RZCrg.hLAro1cdPLGrYkWUHJf1lbsanTzWrnpYCay0IxgRF7k&dib_tag=se&keywords=Realistic+Asset+Creation+with+Adobe+Substance+3D%3A+Create+materials%2C+textures%2C+filters%2C+and+3D+models+using+Substance+3D+Painter%2C+Designer%2C+and+Stager.&qid=1727985694&sprefix=realistic+asset+creation+with+adobe+substance+3d+create+materials%2C+textures%2C+filters%2C+and+3d+models+using+substance+3d+painter%2C+designer%2C+and+stager.%2Caps%2C339&sr=8-1&linkCode=ll1&tag=tekisolves-20&linkId=4f2ba61a4c38d3d18aa02455ffcd69ae&language=en_US&ref_=as_li_ss_tl"
  image_url: "/substance-adobe.jpg"
  rating: "★★★★☆"
